### PR TITLE
npm test script, run tests in detected browsers, locally

### PR DESCRIPTION
**Pull request by darlanmendonca**
following issue https://github.com/minimalist-components/webcomponents/issues/3

when run `npm test`, run tests in all browsers detected

commit pushes/pull requests, in CI, continue run in all browsers specified, in browserstack

### CODE REVIEW

**Comment by darlanmendonca** [comment]
@alencar13 test in your linux pls

**Review by alencar13 — DISMISSED** [review]
Running as expected. Approved!

**Comment by darlanmendonca** [comment]
@alencar13 a last change, to dont run in all browsers, only run in all browsers available from specified list

**Review by alencar13 — APPROVED** [review]
Changes are running correctly.

Approved!

**Pull request merged**
